saic/paste/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import redirect_to

urlpatterns = patterns('saic.paste.views',
    url(r'^live/$', 'live_paste', name='live_paste'),
    url(r'^(?P<pk>\d+)/$', redirect_to, {'url': '/paste/%(pk)s/'}),
    url(r'^(?P<pk>\d+)/(?P<private_key>[a-zA-Z0-9]+)?/?$', redirect_to, {'url': '/paste/%(pk)s/%(private_key)s/'}),
    url(r'^owner/$', redirect_to, {'url': '/owner/all/'}),
    url(r'^owner/anonymous/', 'user_pastes', name='anon_pastes'),
    url(r'^owner/(?P<owner>.+)/', 'user_pastes', name='user_pastes'),
    url(r'^paste/(?P<pk>\d+)/adopt/(?P<private_key>[a-zA-Z0-9]+)?/?$', 'paste_adopt', name='paste_adopt'),
    url(r'^paste/(?P<pk>\d+)/embed/(?P<private_key>[a-zA-Z0-9]+)?/?$', 'paste_embed', name='paste_embed'),
    url(r'^paste/(?P<pk>\d+)/edit/(?P<private_key>[a-zA-Z0-9]+)?/?$', 'paste_edit', name='paste_edit'),
    url(r'^paste/(?P<pk>\d+)/fork/(?P<private_key>[a-zA-Z0-9]+)?/?$', 'paste_fork', name='paste_fork'),
    url(r'^paste/(?P<pk>\d+)/favorite/(?P<private_key>[a-zA-Z0-9]+)?/?$', 'paste_favorite', name='paste_favorite'),
    url(r'^paste/(?P<pk>\d+)/delete/(?P<private_key>[a-zA-Z0-9]+)?/?$', 'paste_delete', name='paste_delete'),
    url(r'^paste/(?P<pk>\d+)/raw/(?P<private_key>[a-zA-Z0-9]+)?/?$', 'paste_raw', name='paste_raw'),
    url(r'^commit/(?P<pk>.+)/adopt/(?P<private_key>[a-zA-Z0-9]+)?/?$', 'commit_adopt', name='commit_adopt'),
    url(r'^commit/(?P<pk>.+)/download/(?P<private_key>[a-zA-Z0-9]+)?/?$', 'commit_download', name='commit_download'),
    url(r'^paste/(?P<pk>\d+)/(?P<private_key>[a-zA-Z0-9]+)?/?$', 'paste_view', name='paste_view'),
    url(r'^users/$', 'users', name='users'),
    url(r'^favorites/$', 'favorites', name='favorites'),
    url(r'^accounts/login/$', 'login', name='login'),
    url(r'^accounts/logout/$', 'logout', name='logout'),
    url(r'^accounts/register/$', 'register', name='register'),
    url(r'^accounts/preference/$', 'preference', name='preference'),
    url(r'^accounts/timezone/$', 'set_timezone', name='set_timezone'),
    url(r'^$', 'paste', name='paste'),
)

saic/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import redirect_to

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/password_reset/$',
        'django.contrib.auth.views.password_reset', name='password_reset'),
    (r'^password_reset/done/$',
        'django.contrib.auth.views.password_reset_done'),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm'),
    (r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete'),
    (r'^search/', include('haystack.urls')),
    url(r'^', include('saic.paste.urls')),
)

saic/paste/models.py
import pytz

from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

import timezone

from datetime import datetime

from saic.settings import generate_icon

timezones = [(tz, tz) for tz in pytz.common_timezones]

class DateTimeFieldTZ(models.DateTimeField):
    def __init__(self, *args, **kwargs):
        super(DateTimeFieldTZ, self).__init__(*args, **kwargs)

    def pre_save(self, model_instance, add):
        if self.auto_now or (self.auto_now_add and add):
            value = datetime.utcnow().replace(tzinfo=timezone.utc)
            setattr(model_instance, self.attname, value)
            return value
        else:
            return super(models.DateTimeField, self).pre_save(model_instance, add)

    def get_prep_value(self, value):
        value = self.to_python(value)
        if value is not None and settings.USE_TZ and timezone.is_naive(value):
            # Always store times in UTC regardless of TIME_ZONE setting
            default_timezone = timezone.utc
            value = timezone.make_aware(value, default_timezone)
        return value


class Set(models.Model):
    owner = models.ForeignKey(User, null=True, blank=True, default=None)
    description = models.CharField(max_length=255)
    repo = models.CharField(max_length=100)
    fork = models.ForeignKey('Commit', null=True, blank=True, default=None, on_delete=models.SET_NULL)
    private = models.BooleanField(default=False)
    anyone_can_edit = models.BooleanField(default=False)
    private_key = models.CharField(max_length=30)
    expires = models.DateTimeField(null=True)
    created = models.DateTimeField(auto_now_add=True)
    views = models.IntegerField()

    class Meta:
        ordering = ['-created']
        get_latest_by = 'created'

    @property
    def email(self):
        return self.owner.preference.email

    @property
    def active_private_key(self):
        """ For use in templates. """
        return self.private_key if self.private else ''

    @property
    def ordered_commits(self):
        return self.commit_set.order_by('-created', ).all

    def __unicode__(self):
        return '%s: %s' % (self.repo, self.description)


class Commit(models.Model):
    commit = models.CharField(max_length=255)
    parent_set = models.ForeignKey(Set)
    created = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, null=True, blank=True, default=None)
    diff = models.TextField(null=True, blank=True)
    views = models.IntegerField()

    @property
    def email(self):
        return self.owner.preference.email if self.owner else "Anonymous"

    @property
    def short(self):
        return self.commit[:8]

    class Meta:
        ordering = ['-created']
        get_latest_by = 'created'

    def __unicode__(self):
        return '%s by %s' % (self.commit, self.owner)


class Comment(models.Model):
    parent = models.TextField(null=True, blank=True, default=None)
    diff = models.TextField(blank=True)
    commit = models.ForeignKey(Commit)
    owner = models.ForeignKey(User)
    comment = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    @property
    def email(self):
        return self.owner.preference.email

    def __unicode__(self):
        return '%s: %s' % (self.owner, self.commit.commit)


class Paste(models.Model):
    absolute_path = models.CharField(max_length=2048)
    filename = models.CharField(max_length=255)
    paste = models.TextField()
    paste_formatted = models.TextField()
    language = models.CharField(max_length=100)
    revision = models.ForeignKey(Commit)
    created = models.DateTimeField(auto_now_add=True)
    priority = models.IntegerField()

    class Meta:
        ordering = ['priority']

    def __unicode__(self):
        return '%s: %s' % (self.filename, self.revision.commit)


class Favorite(models.Model):
    parent_set = models.ForeignKey(Set)
    user = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return '%s: %s' % (self.user, self.parent_set.repo)


class Preference(models.Model):
    user = models.OneToOneField(User, unique=True)
    mask_email = models.BooleanField(default=False)
    masked_email = models.CharField(max_length=256)
    default_anonymous = models.BooleanField()
    timezone = models.CharField(blank=True, choices=timezones, default='UTC', max_length=20)
    gravatar = models.URLField(blank=True)

    @property
    def email(self):
        if self.mask_email:
            return self.masked_email
        return self.user.email

    def __unicode__(self):
        return "%s <%s>" % (self.user, self.masked_email)


def get_or_create_preference(user):
    try:
        preference = Preference.objects.get(user=user)
    except Preference.DoesNotExist:
        try:
            at, email = str(user.email).split('@')
            masked_email = '%s%s@%s' % (at[:2], len(at[2:]) * '*', email)
        except ValueError, e:
            email = user.username
            masked_email = ''
        return Preference.objects.create(
                user=user, masked_email=masked_email, 
                gravatar=generate_icon(user.email)
        )
    return preference

User.preference = property(lambda u: get_or_create_preference(u))

saic/paste/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from models import *

from pygments import lexers

# Add preferred lexers here. This list will not be explicitly sorted. 
preferred_lexers = [
        'TextLexer', 
        'ActionScriptLexer', 
        'CLexer', 
        'CSharpLexer', 
        'CppLexer', 
        'CommonLispLexer', 
        'CssLexer',
        'DiffLexer',
        'ErlangLexer',
        'HaskellLexer',
        'HtmlLexer',
        'JavaLexer',
        'JavascriptLexer',
        'LuaLexer',
        'ObjectiveCLexer',
        'PerlLexer',
        'PhpLexer',
        'PythonLexer',
        'RubyLexer',
        'ScalaLexer',
        'SchemeLexer',
        'SqlLexer',
        'TexLexer',
        'XmlLexer',
]

def unwrap_lexer(lang):
    language = lexers.LEXERS[lang]
    lex, name, alias, exts, mime = language
    if len(exts):
        return ('%s;%s' % (lang, exts[0][1:]), name)
    return ('%s;.txt' % lang, name)


# Create our list of languages
base_languages = map(unwrap_lexer, lexers.LEXERS)
languages = map(unwrap_lexer, preferred_lexers)

# Only sort the base languages because we assume the preferred list is
# already in the desired sorting
base_languages.sort()

# Add the base cases and base languages
languages.append(('TextLexer;.txt', '----'),)
languages.extend(base_languages)

class CommitMetaForm(forms.Form):
    """These correspond to a particular commit or iteration of a paste."""
    anonymous = forms.BooleanField(required=False)

class SetMetaForm(forms.Form):
    """Extra set options"""
    anyone_can_edit = forms.BooleanField(required=False)
    private = forms.BooleanField(required=False)
    expires = forms.ChoiceField(
        choices = (
            ("never", "Never"),
            ("hour", "1 Hour"),
            ("day", "1 Day"),
            ("month", "1 Month"),
        ), required=False
    )

class SetForm(forms.Form):
    description = forms.CharField(max_length=256, required=False,
            widget=forms.widgets.TextInput(attrs={
                'placeholder': 'add a paste description...'
            }))

    def clean_description(self):
        d = self.cleaned_data.get('description')
        if d is None:
            return d
        if d == 'add a paste description...':
            return ''
        return d


class PasteForm(forms.Form):
    priority = forms.IntegerField(initial=0)
    filename = forms.CharField(max_length=256, required=False,
            widget=forms.widgets.TextInput(attrs={
                'placeholder': 'add a file name...',
                'class': 'filename'
            }))

    def clean_filename(self):
        d = self.cleaned_data.get('filename')
        if d is None:
            return d
        if d == 'add a file name...':
            return ''
        return d

    paste = forms.CharField(widget=forms.Textarea, required=False)
    language = forms.ChoiceField(
            choices=languages,
            required=False,
            widget=forms.Select(attrs={'tabindex': -1})
    )


class UserCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args,
**kwargs)

    class Meta:
        model = User
        exclude = ('date_joined', 'last_login', 'password')

    def save(self, commit=True):
        """See ProfileForm for this error."""
        model = super(UserCreationForm, self).save(commit=False)
        model.username = self.cleaned_data['username']

        if commit:
            model.save()

        return model


class CommentForm(forms.Form):
    comment = forms.CharField(required=True, widget=forms.Textarea)

class PreferenceForm(forms.ModelForm):
    class Meta:
        model = Preference
        exclude = ('user','masked_email','gravatar')

saic/paste/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset='UTF-8'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700|Lato:400,700|Droid+Sans+Mono' rel='stylesheet'>
    <link rel='stylesheet' media='screen' href='{{ STATIC_URL }}/css/base.css'>
    <link rel='stylesheet' media='print' href='{{ STATIC_URL }}/css/base-print.css'>
    <script src='{{ STATIC_URL }}/js/jquery-1.7.1.min.js'></script>
    {% block jsheader %}{% endblock %}
  </head>
  <body>
      <nav class='top-bar'>
          <ul>
              <li><a title='Create a new paste.' href='{% url paste %}'>New Paste</a></li>
              <!--<li><a title='Search for pastes by others.' href='/search/'>Search</a></li>-->
              <li><a title='Views a list of users' href='{% url users %}'>Users</a></li>
              <li><a title='All pastes' href='{% url user_pastes owner='all' %}'>All Pastes</a></li>
              <li>|</li>
              {% if user.is_authenticated %}
              <li><a title='View a list of your contributed pastes.' href='{% url user_pastes owner=user.pk %}'>Contributed ({{ user.set_set.all.count }})</a></li>
              <li><a title='View a list of your favorited pastes.' href='{% url favorites %}'>Favorites ({{ user.favorite_set.all.count }})</a></li>
              <li><a title='Modify your user preference.' href='{% url preference %}'>Preferences</a></li>
              <li><a title='Logout' href='{% url logout %}'>Logout</a></li>
              {% else %}
              <li><a title='Login' href='{% url login %}'>Login</a></li>
              <li><a title='Register' href='{% url register %}'>Register</a></li>
              {% endif %}
          </ul>
          <a href='{% url paste %}'><img alt='quark-paste' src='{{ STATIC_URL }}/img/logo.png'></a>
      </nav>
      <div class='clear'></div>
      <div id='wrapper'>
          {% block content %}
          {% endblock %}
      </div>
  </body>
</html>

saic/paste/templates/embed.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <title>GitPaste Embedding</title>
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700|Lato:400,700|Droid+Sans+Mono' rel='stylesheet'>
        <link rel='stylesheet' media='print' href='{{ STATIC_URL }}/css/base-print.css'>
        <link rel='stylesheet' media='screen' type='text/css' href='{{ STATIC_URL }}/css/view.css'>
        <link rel='stylesheet' media='all' type='text/css' href='{{ STATIC_URL }}/css/pygments/{{ theme }}.css'>
    </head>
    <body>
        <div class='paste'>
            <div>
                {{ paste.paste_formatted|safe }}
            </div>
        </div>
    </body>
</html>

saic/paste/templates/favorites.html
{% extends "base.html" %}
{% load elapsed %}
{% load tz %}

{% block title %} Login {% endblock %}

{% block jsheader %}
<link rel='stylesheet' media='all' type='text/css' href='{{ STATIC_URL }}/css/favorites.css'>
{% endblock %}

{% block content %}
<div id='favorites'>
  <h1>
    {% if favorites.count %}
       Favorites ({{ favorites.count }})
    {% else %}
      Favoriteless
    {% endif %}
  </h1>
  <div class='entry'>
    <div>
      {% for favorite in favorites %}
        {% with favorite.parent_set as set %}
          <div>
            <a href='{% url paste_view pk=set.pk %}'>Paste {{ set.pk }}{% if set.description %}: {{ set.description }}{% endif %}</a>
            <br>
            {{ set.commit_set.all.count }} commit{{ set.commit_set.all.count|pluralize }}
            {% with set.commit_set.latest as latest %}
              <span class='date' title='{{ latest.created|localtime }}'>
                {{ latest.created|elapsed }} by 
                {% if latest.owner %}you{% else %}{{ latest.email }}{% endif %}.
              </span>
            {% endwith %}
          </div>
        {% endwith %}
      {% empty %}
        <div>
          <h1 class='center'>What is a favorite if you don't show love?</h1>
          <p class='tiny gray center'>(a.k.a. go <a href='/search/'>find pastes</a> to favorite)</p>
        </div>
      {% endfor %}
    </div>
    <div class='clear'></div>
  </div>
</div>
{% endblock %}

saic/paste/templates/login.html
{% extends "base.html" %}

{% block title %} Login {% endblock %}

{% block jsheader %}
<link rel='stylesheet' media='all' type='text/css' href='{{ STATIC_URL }}/css/login.css'>
{% endblock %}

{% block content %}
<div id='login'>
  <form method='POST' id='paste-form'>
    <h1>Login</h1>
    <div class='entry'>
      <div>
        <div> <label>Username: </label> {{ form.username }} </div>

        {% if form.username.errors %}
          <div>{{ form.username.errors }}</div>
        {% endif %}

        <div> <label>Password: </label> {{ form.password}} </div>

        {% if form.password.errors %}
          <div>{{ form.password.errors }}</div>
        {% endif %}

      </div>
      <div class='clear'></div>
    </div>
    <div class='register'>
      <input type='submit' value='Login'>
    </div>
    <div>
        <br>
        {{ form.non_field_errors }}
    </div>
    {% csrf_token %}
  </form>
</div>
<script src='{{ STATIC_URL }}/js/paste.js'></script>
{% endblock %}

saic/paste/templates/paste-view.html
{% extends "base.html" %}
{% load elapsed %}
{% load markup %}
{% load tz %}

{% block title %}
{% if paste_set.description %}
gitpaste.com - "{{ paste_set.description }}"
{% else %}
gitpaste.com - anonymous paste
{% endif %}
{% endblock %}

{% block jsheader %}
<script src='{{ STATIC_URL }}/js/jquery.formset.min.js'></script>
<script src='{{ STATIC_URL }}/js/ba-linkify.min.js'></script>
<link rel='stylesheet' media='all' type='text/css' href='{{ STATIC_URL }}/css/pygments/tango.css'>
<link rel='stylesheet' media='screen' type='text/css' href='{{ STATIC_URL }}/css/view.css'>
<link rel='stylesheet' media='screen' type='text/css' href='{{ STATIC_URL }}/css/markdown.css'>
{% if use_icons %}
<link rel='stylesheet' media='screen' type='text/css' href='{{ STATIC_URL }}/css/view-icons.css'>
{% endif %}
{% endblock %}

{% block content %}
<section class='meta'>
  <h1>
    {{ paste_set.commit_set.all.count }}
    Revision{{ paste_set.commit_set.all.count|pluralize }}
  </h1>
  <ul class='revisions'>
    {% for commit in paste_set.ordered_commits %}
      {% if commit.commit == commit_current.commit %}
        <li class='active'>
      {% else %}
        <li>
      {% endif %}
      <a title='{{ commit.commit.views }} view{{ commit.commit.views|pluralize }}' href='{% url paste_view pk=paste_set.pk private_key=paste_set.private_key %}?commit={{ commit.commit }}'>{{ commit.commit|slice:":8"}}</a>
      <span class='author'>
        {% if commit.owner %}
            <a href='{% url user_pastes owner=commit.owner.pk %}'>{{ commit.email }}</a>
        {% else %}
            <a href='{% url anon_pastes %}'>Anonymous</a>
        {% endif %}
      </span> 
      <span class='date' title="{{ commit.created|localtime }}">
        {{ commit.created|elapsed }}.    </span> </li>
    {% endfor %}
  </ul>
  {% if user.is_authenticated %}
    <br>
    {% if not commit_current.parent_set.owner %}
      <div class="sidebar-message">
        <span class='alert'>Hey! This paste is not owned by anyone.
          <a href='{% url paste_adopt pk=commit_current.parent_set.pk %}'>Adopt it!</a>
        </span>
      </div>
    {% endif %}
    {% if commit_current.parent_set.owner == user %}
      <div class="sidebar-message">
        <a class='alert' href='{% url paste_delete pk=commit_current.parent_set.pk %}'>delete this entire paste</a>
      </div>
    {% endif %}
  {% endif %}
</section>
<div id='pastes'>
  {% if paste_set.private %}
    <div class='private-note entryless'>
      <div class='entry-header'>
        <span>
          This paste is <strong>private</strong>, you'll need this special URL to
          {% if not paste_set.owner_id or user.id != paste_set.owner_id %}revisit{% else %}share{% endif %} it:
          <input type="text" size="75" value="{{ site }}{% url paste_view pk=paste_set.pk private_key=paste_set.private_key %}" readonly>
        </span>
      </div>
    </div>
  {% endif %}
  <div class='entryless info'>
    <div class='small entry-header'>
      {% if user.is_authenticated %}
      <span favorite={{ favorited }} id='favorite-toggle'>
        {% if favorited %}
          <img title='Click to remove this post from your favorites' align='left' alt='favorite' height='32px' src='{{ STATIC_URL }}/img/favorite.png'>
        {% else %}
          <img title='Click to favorite this post' align='left' alt='not-favorite' height='32px' src='{{ STATIC_URL }}/img/not-favorite.png'>
        {% endif %}
        </span>
      {% endif %}
    <span class='header'>
      {% if USE_ICONS %}
        {% if commit_current.owner %}
        <a href='{% url user_pastes owner=commit_current.owner.pk %}'>
          <img title='User pastes' class='gravatar-community' alt='User' src='{{ commit_current.owner.preference.gravatar }}'></a>
        {% else %}
          <a href='{% url anon_pastes %}'><img class='gravatar-community' alt='Anonymous' src='{{ STATIC_URL }}/img/default-icon.png'></a>
        {% endif %}
      {% endif %}
      paste: {{ paste_set.pk }} / commit: {{ commit_current.commit|slice:":8" }}
      <span class="paste-actions">
      {% if editable %}
          <a title='Find the bug.' href='{% url paste_edit pk=paste_set.pk private_key=paste_set.active_private_key %}?commit={{ commit_current.commit }}'>edit</a>
      {% else %}
          <span title='This paste is not editable' class='unlink gray'>edit</span>
      {% endif %}
      {% if user.is_authenticated %}
        <a title='Because you can do much better.' href='{% url paste_fork pk=paste_set.pk private_key=paste_set.active_private_key %}?commit={{ commit_current.commit }}'>fork</a>
      {% else %}
      <span title='Login to fork' class='unlink gray'>fork</span>
      {% endif %}
      {% if user.is_authenticated and not commit_current.owner %}
          <a title='How would you feel?' href='{% url commit_adopt pk=commit_current.pk private_key=paste_set.active_private_key %}'>adopt</a>
      {% endif %}
      <a title='Download paste' href='{% url commit_download pk=commit_current.pk private_key=paste_set.active_private_key %}'>download</a>
      {% if commit_current.diff %}
        <span id='diff-toggle' class='link' title='You are not to blame'>diff</span>
      {% else %}
        <span class='gray unlink' title='No diff available'>diff</span>
      {% endif %}
      </span>
    </span>
      <br>
      {% if paste_set.description %}"{{ paste_set.description }}"{% endif %}
      {% if commit_current.owner %} by <strong><a href='{% url user_pastes owner=commit_current.owner.pk %}'>{{ commit_current.email }}</a></strong> {% endif %}
      <span class='date' title="{{ commit_current.created|localtime }}">
        {{ commit_current.created|elapsed }}
        with {{ commit_current.views }} 
        view{{ commit_current.views|pluralize }}.
      </span>
      {% if paste_set.fork %}
        <br>
        <em class='light'>Fork of                
          {% if paste_set.fork.parent_set.owner %}
            <a href='{% url user_pastes owner=paste_set.fork.parent_set.owner.pk %}'>{{ paste_set.fork.parent_set.email }}</a>
          {% else %}
            <a href='{% url anon_pastes %}'>Anonymous</a>
          {% endif %} at commit 
          <a href='{% url paste_view pk=paste_set.fork.parent_set.pk %}?commit={{ paste_set.fork.commit }}'>{{ paste_set.fork.commit|slice:":8" }}</a>
        </em>
      {% endif %}
    </div>
  </div>

  {% if commit_current.diff %}
  <div id='diff' class='entry hidden'>
    <div class='file'><div>Diff</div></div>
    <div class='paste'>
      <div>
        {{ commit_current.diff|safe }}
      </div>
    </div>
  </div>
  {% endif %}

  {% for paste in pastes %}
    <div class='entry'>
      <div class='description'>
        <div>
          {{ paste.description }}
        </div>
      </div>
      <div class='file'>
        <div class='file-download'>
            <a title='You should just fork it.' href='{% url paste_raw pk=paste.pk private_key=paste_set.active_private_key %}?download=true'>download</a>
            <a title='Embedding it.' href='{% url paste_embed pk=paste.pk private_key=paste_set.active_private_key %}'>embed</a>
        </div>
        <div id='file-{{ paste.pk }}'>
          {{ paste.filename }} <a href='#file-{{ paste.pk }}'>#</a>
          <a title='Too raw for you.' href='{% url paste_raw pk=paste.pk private_key=paste_set.active_private_key %}'>raw</a>
        </div>
      </div>
      <div class='paste'>
        <div>
          {{ paste.paste_formatted|safe }}
        </div>
      </div>
    </div>
    <div class='clear'></div>
  {% endfor %}
  {% if commit_current.comment_set.exists %}
    <div class='entry-comment comment'>
      <h1>{{ commit_current.comment_set.all.count }} Comment{{ commit_current.comment_set.all.count|pluralize }}</h1>
      {% for comment in commit_current.comment_set.all %}
        <div name='comment-{{ comment.pk }}' class='comment-index'>
        {% if USE_ICONS %}
            <h1 class='author {% if comment.owner == commit_current.owner %}committer{% endif %}' style='background: url({{ comment.owner.preference.gravatar }}) no-repeat left center #DDD'>
          {% else %}
            <h1 class='author {% if comment.owner == commit_current.owner %}committer{% endif %}'> 
          {% endif %}
            <a href='{% url user_pastes owner=comment.owner.pk %}'>
              {{ comment.email }}</a> 
            <a href='#comment-{{ comment.pk }}' id='comment-{{ comment.pk }}'>#</a>
          </h1>
          <div class='markdown'>{{ comment.comment|markdown:"safe" }}</div>
        </div>
      {% empty %}
        <div name='comment-blank' class='comment-index'>
          {% if user.is_authenticated %}
              <pre>If only there were comments...</pre>
          {% else %}
              <pre>If only there were comments... Maybe <a href='{% url login %}'>login</a> and add one?</pre>
          {% endif %}
        </div>
      {% endfor %}
    </div>
  {% endif %}
  {% if user.is_authenticated %}
    <div class='entry comment'>
      <h1 class='header'>Comment</h1>
      <p class='tiny gray'>Hint: You can use <a href='http://daringfireball.net/projects/markdown/'>markdown</a> in your comment.</p>
      <form method='POST'>
        {{ comment_form.comment }}
        {% csrf_token %}
        <input type='submit' value='Add Comment'>
      </form>
    </div>
  {% endif %}
</div>
<script>var set = "{{ commit_current.parent_set.pk }}";</script>
<script src='{{ STATIC_URL }}/js/view.js'></script>
{% endblock %}

saic/paste/templates/users.html
{% extends "base.html" %}
{% load humanize %}

{% block title %} Login {% endblock %}

{% block jsheader %}
<link rel='stylesheet' media='all' type='text/css' href='{{ STATIC_URL }}/css/favorites.css'>
{% endblock %}

{% block content %}
<div id='favorites'>
  <h1>{{ count }} Member{{ count|pluralize }}</h1>
  <h2 class='pages'>
    {% if users.has_previous %}
        <a href="?page={{ users.previous_page_number }}">prev</a>
    {% endif %}

    <span class="current">
        Page {{ users.number }} of {{ users.paginator.num_pages }}
    </span>

    {% if users.has_next %}
        <a href="?page={{ users.next_page_number }}">next</a>
    {% endif %}
  </h2>
  <div class='entry'>
    <div>
      <div class='user'>
        <a href='{% url anon_pastes %}'>
          {% if USE_ICONS %}
            <img class='gravatar-community' title='Profile' src='{{ STATIC_URL }}/img/default-icon.png'>
          {% endif %}
          Anonymous</a>
        <br>
        {{ anons.all.count }} paste{{ anons.all.count|pluralize }}.
      </div>
      {% for user in users.object_list %}
      <div class='user'><a href='{% url user_pastes owner=user.pk %}'>
          {% if USE_ICONS %}
            <img class='gravatar-community' title='Profile' src='{{ user.preference.gravatar }}'>
          {% endif %}
          {{ user.preference.email }}</a>
          <br>
          {% if user.public_sets.count %}
            {{ user.set_set.all.count }} paste{{ user.set_set.all.count|pluralize }}.
          {% else %}
            A pasteless user.
          {% endif %}
        </div>
      {% endfor %}
    </div>
    <div class='clear'></div>
  </div>
</div>
{% endblock %}